#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:

hours=0
while [ $hours -le 12 ]
do
    echo "Hour: $hours";
    minute=1;
    while [ $minute -lt 60 ]
    do
        echo "$minute";
        minute=$((minute + 1));
    done
    hours=$((hours + 1))
done