#!/usr/bin/env bash
# Bash script that displays the content of the current directory,
# In a list format,
# Where only the part of the name after the first dash is displayed

for f in *
do
	echo "${f/*-/}"
done